[fix]修复最版本esp8266 ping不通的问题
RT-Thread-packages/at_device pull request #207
Opened 2024-03-21 09:42 UTC by Yaochenger

修复最新版本的at组件esp8266 ping不通的问题 支持固件版本v1.7.1以上
固件地址：https://docs.ai-thinker.com/%E5%9B%BA%E4%BB%B6%E6%B1%87%E6%80%BB

2024-03-21 09:44 UTC, Rbb666 approved these changes

2024-03-22 02:19 UTC, mysterywolf commented
这个是rt-thread那个commit或者哪个版本引入的？可以找到commit id嘛？是否需要做一个rt-thread版本区分？

2024-03-22 13:09 UTC, Rbb666 commented
@Yaochenger

2024-04-09 22:20 UTC, mysterywolf commented
https://github.com/RT-Thread-packages/at_device/pull/203 引入的这个问题

2024-04-11 08:01 UTC, Rbb666 commented on class/esp8266/at_device_esp8266.c
> +
多了缩进，要格式化下

2024-04-13 01:51 UTC, Rbb666 commented
@mysterywolf  满老师看看

2024-04-16 02:53 UTC, mysterywolf requested changes

2024-04-16 02:53 UTC, mysterywolf commented on class/esp32/at_socket_esp32.c
> +        extern unsigned int ESP32_GMR_AT_VERSION;
不要这么改，用个函数包一下这个全局变量 然后返回这个全局变量的值

2024-04-17 00:04 UTC, mysterywolf approved these changes

2024-04-17 00:05 UTC, mysterywolf approved these changes

2024-04-17 00:06 UTC, merged