修复ML307A的一些连接问题
RT-Thread-packages/at_device pull request #212
Opened 2024-06-25 02:17 UTC by VirensCn

对ML307模块进行了一些优化，解决偶尔出现断连的情况

2024-06-25 17:24 UTC, mysterywolf requested changes

2024-06-25 17:24 UTC, mysterywolf commented on class/ml307/at_device_ml307.c
> -#endif
为什么把这个删了？

2024-06-27 08:52 UTC, closed without merging

2024-06-27 08:53 UTC, VirensCn commented on class/ml307/at_device_ml307.c
> -#endif
搞错了，当时测试的时候简化掉了。

2024-06-27 08:54 UTC, VirensCn commented on class/ml307/at_device_ml307.c
> -#endif
目前这个Ml307还没有配置项选择，我提交了一个，但是机器人好像给拒绝了，说测试环境没跑过，我是直接复制的305，改了下